// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import { normalizePgConnectionString } from "./lib/normalizePgConnectionString";

/**
 * `prisma migrate deploy` precisa de conexão direta ao Postgres. URLs com pooler Neon
 * (`-pooler` no hostname → PgBouncer) costumam falhar no advisory lock (P1002).
 *
 * Ordem: `DATABASE_URL_UNPOOLED` (explícito) → derivação Neon (remove `-pooler.` do host)
 * → `DATABASE_URL`.
 */
function resolveMigrateDatasourceUrl(): string {
  const explicit = process.env["DATABASE_URL_UNPOOLED"];
  if (explicit?.trim()) return normalizePgConnectionString(explicit.trim());

  const pooled = process.env["DATABASE_URL"];
  if (!pooled?.trim()) return "";

  try {
    const u = new URL(pooled);
    // Neon: host típico `ep-xxx-pooler.region.aws.neon.tech` → direto `ep-xxx.region.aws.neon.tech`
    if (u.hostname.includes("-pooler.")) {
      u.hostname = u.hostname.replace("-pooler.", ".");
      return normalizePgConnectionString(u.toString());
    }
  } catch {
    /* ignore parse errors, fall through */
  }

  return normalizePgConnectionString(pooled);
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: resolveMigrateDatasourceUrl(),
  },
});
