// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migrações precisam de conexão direta ao Postgres. URLs com pooler Neon (-pooler)
    // (PgBouncer) costumam falhar no advisory lock do Prisma (P1002 no deploy).
    // Na Vercel: defina DATABASE_URL_UNPOOLED com a connection string "direct" do Neon.
    url: process.env["DATABASE_URL_UNPOOLED"] ?? process.env["DATABASE_URL"],
  },
});
